Fix 180: Add environment variables to Click CLI options
nexB/python-inspector pull request #187
Opened 2024-08-13 16:07 UTC by calizarr

This will add environment variables as extra options for the index-url flag. Click will [split on whitespace for multiple values by default.](https://thirdparty.aboutcode.org/pypi/simple/)

Added a possibly unnecessary test to make sure that flags override environment variables. 

Signed-off-by: Cesar Lizarraga <calizarr@gmail.com>

2024-08-14 12:09 UTC, pombredanne requested changes
@calizarr Thanks! Looking good.
Do you mind to add a DCO signoff, at least once in the PR comments? No need to amend your commits

@TG1999 we need to enable the DCO bot here :)

2024-08-15 17:01 UTC, calizarr commented
I believe I've just rebased and added my signature.

2024-08-15 18:56 UTC, TG1999 commented
@calizarr not all the commits have the sign-off

2024-08-15 19:14 UTC, calizarr commented
Alright, I'll try again

2024-08-15 19:25 UTC, TG1999 commented
Something like this

Signed-off-by: Name <email>

in the end of PR description

2024-08-26 19:13 UTC, calizarr commented
All commits should be signed off now.

2025-03-10 16:24 UTC, MarcelBochtler commented
@pombredanne what is missing from this PR to get it merged?
We also need #180 fixed, and I would like to avoid working around it in ORT.

2025-06-03 08:34 UTC, merged